import type { AdminApplicationCaseDetail, AdminApplicationCaseRow } from "./types";

const applicationCaseRow: AdminApplicationCaseRow = {
  id: 1,
  userId: 10,
  userEmail: "user@example.com",
  companyName: "Example Co",
  jobTitle: "Frontend Engineer",
  postingDate: "2026-06-01",
  deadlineDate: "2026-06-30",
  sourceType: "TEXT",
  status: "READY",
  favorite: false,
  archivedAt: null,
  deletedAt: null,
  createdAt: "2026-06-01T00:00:00Z",
  updatedAt: "2026-06-02T00:00:00Z",
  latestPostingRevision: 2,
  latestJobAnalysisAt: "2026-06-02T00:00:00Z",
  latestCompanyAnalysisAt: "2026-06-02T00:00:00Z",
};

const applicationCaseDetail: AdminApplicationCaseDetail = {
  applicationCase: applicationCaseRow,
  jobPostings: [],
  jobAnalyses: [
    {
      id: 11,
      applicationCaseId: 1,
      jobPostingId: 21,
      jobPostingRevision: 2,
      employmentType: "FULL_TIME",
      experienceLevel: "MID",
      requiredSkills: "[\"React\"]",
      preferredSkills: null,
      duties: null,
      qualifications: null,
      difficulty: "NORMAL",
      summary: "Summary",
      evidence: "Evidence text",
      ambiguousConditions: "Ambiguous conditions",
      confirmedAt: null,
      adminMemo: null,
      createdAt: "2026-06-02T00:00:00Z",
    },
  ],
  companyAnalyses: [
    {
      id: 12,
      applicationCaseId: 1,
      jobPostingId: 21,
      jobPostingRevision: 2,
      companySummary: "Company summary",
      recentIssues: null,
      industry: "SaaS",
      competitors: null,
      interviewPoints: null,
      sources: null,
      verifiedFacts: "Verified facts",
      aiInferences: "AI inferences",
      sourceType: "WEB",
      checkedAt: "2026-06-02T00:00:00Z",
      refreshRecommendedAt: "2026-06-09T00:00:00Z",
      confirmedAt: null,
      adminMemo: null,
      createdAt: "2026-06-02T00:00:00Z",
    },
  ],
  usageLogs: [],
};

void applicationCaseDetail;
