-- C 전략 일정과 사용자 메모/일정/리마인더를 저장하는 플래너 테이블.
-- 기존 career_goal/learning_plan 은 유지하고, 자유형 메모·범위 일정·알림·오버레이 상태를 별도 관리한다.

CREATE TABLE IF NOT EXISTS planner_memo (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    title VARCHAR(120) NULL,
    content TEXT NULL,
    color VARCHAR(20) NOT NULL DEFAULT 'yellow',
    pinned TINYINT(1) NOT NULL DEFAULT 0,
    overlay_visible TINYINT(1) NOT NULL DEFAULT 0,
    opacity DECIMAL(3,2) NOT NULL DEFAULT 1.00,
    application_case_id BIGINT NULL,
    fit_analysis_id BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    PRIMARY KEY (id),
    KEY idx_planner_memo_user (user_id, pinned, updated_at),
    KEY idx_planner_memo_case (application_case_id),
    KEY idx_planner_memo_fit (fit_analysis_id),
    CONSTRAINT fk_planner_memo_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_planner_memo_case FOREIGN KEY (application_case_id) REFERENCES application_case (id) ON DELETE SET NULL,
    CONSTRAINT fk_planner_memo_fit FOREIGN KEY (fit_analysis_id) REFERENCES fit_analysis (id) ON DELETE SET NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS planner_schedule_item (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT NULL,
    kind VARCHAR(30) NOT NULL DEFAULT 'TASK',
    status VARCHAR(30) NOT NULL DEFAULT 'PLANNED',
    all_day TINYINT(1) NOT NULL DEFAULT 0,
    timing_precision VARCHAR(20) NOT NULL DEFAULT 'MINUTE',
    start_at DATETIME NOT NULL,
    end_at DATETIME NULL,
    timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Seoul',
    application_case_id BIGINT NULL,
    fit_analysis_id BIGINT NULL,
    source_type VARCHAR(40) NOT NULL DEFAULT 'MANUAL',
    source_ref VARCHAR(120) NULL,
    source_snapshot_json JSON NULL,
    overlay_visible TINYINT(1) NOT NULL DEFAULT 0,
    opacity DECIMAL(3,2) NOT NULL DEFAULT 1.00,
    pinned TINYINT(1) NOT NULL DEFAULT 0,
    click_through TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    PRIMARY KEY (id),
    KEY idx_planner_schedule_user_time (user_id, start_at, end_at),
    KEY idx_planner_schedule_case (application_case_id, start_at),
    KEY idx_planner_schedule_fit (fit_analysis_id),
    KEY idx_planner_schedule_source (source_type, source_ref),
    CONSTRAINT fk_planner_schedule_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_planner_schedule_case FOREIGN KEY (application_case_id) REFERENCES application_case (id) ON DELETE SET NULL,
    CONSTRAINT fk_planner_schedule_fit FOREIGN KEY (fit_analysis_id) REFERENCES fit_analysis (id) ON DELETE SET NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS planner_schedule_reminder (
    id BIGINT NOT NULL AUTO_INCREMENT,
    schedule_item_id BIGINT NOT NULL,
    remind_at DATETIME NOT NULL,
    offset_minutes INT NULL,
    channels_json JSON NULL,
    sound_enabled TINYINT(1) NOT NULL DEFAULT 1,
    vibration_enabled TINYINT(1) NOT NULL DEFAULT 1,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    sent_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_planner_reminder_due (status, remind_at),
    KEY idx_planner_reminder_item (schedule_item_id, remind_at),
    CONSTRAINT fk_planner_reminder_item FOREIGN KEY (schedule_item_id) REFERENCES planner_schedule_item (id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
